name: modify-release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      tag_name:
        required: true
        type: string

permissions:
  contents: write

jobs:
  modify-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
      - name: NPM install
        run:
          npm ci --no-audit
      - name: Build
        run:
          task build
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ inputs.tag_name }} ./dist/*
      - name: Rename Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release edit ${{ inputs.tag_name }} --title ${{ inputs.version }}
