on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-test
          include-v-in-tag: false
          pull-request-title-pattern: "chore${scope}: :bookmark: release${component} ${version}"
      - name: Extract Version Number
        uses: actions/github-script@v6
        id: extract-version
        if: ${{ steps.release.outputs.pr || steps.release.outputs.release_created }}
        env:
          PR_TITLE: ${{ steps.release.outputs.pr && fromJSON(steps.release.outputs.pr).title || ''}}
        with:
          script: |
            const { PR_TITLE } = process.env
            let ver = "";

            if (PR_TITLE !== "") {
              const pr_splitted = PR_TITLE.split(" ");
              ver = pr_splitted[pr_splitted.length - 1];
            }
            if ('${{ steps.release.outputs.release_created }}' !== "") {
              ver = "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
            }

            return ver;
      - uses: ./.github/workflows/modify-release-pr.yml
        if: ${{ steps.release.outputs.pr && !steps.release.outputs.release_created }}
        with:
          version: ${{ steps.extract-version.outputs.result }}
          pr-number: ${{ fromJSON(steps.release.outputs.pr).number }}
        secrets: inherit
      - uses: ./.github/workflows/modify-release.yml
        if: ${{ steps.release.outputs.release_created }}
        with:
          version: ${{ steps.extract-version.outputs.result }}
          tag_name: ${{ steps.release.outputs.tag_name }}
        secrets: inherit