on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.result }}
      to_modify_pr: ${{ steps.release.outputs.pr && !steps.release.outputs.release_created }}
      to_modify_release: ${{ steps.release.outputs.release_created }}
      pr_number: ${{ steps.release.outputs.pr && fromJSON(steps.release.outputs.pr).number || '' }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-test
          include-v-in-tag: false
          pull-request-title-pattern: "chore${scope}: :bookmark: release${component} ${version}"
      - name: Extract Version Number
        uses: actions/github-script@v6
        id: extract-version
        if: ${{ steps.release.outputs.pr || steps.release.outputs.release_created }}
        env:
          PR_TITLE: ${{ steps.release.outputs.pr && fromJSON(steps.release.outputs.pr).title || ''}}
        with:
          script: |
            const { PR_TITLE } = process.env
            let ver = "";

            if (PR_TITLE !== "") {
              const pr_splitted = PR_TITLE.split(" ");
              ver = pr_splitted[pr_splitted.length - 1];
            }
            if ('${{ steps.release.outputs.release_created }}' !== "") {
              ver = "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
            }

            return ver;
  modify-release-pr:
    needs: release-please
    uses: ./.github/workflows/modify-release-pr.yml
    if: ${{ needs.release-please.outputs.to_modify_pr }}
    with:
      version: ${{ needs.release-please.outputs.version }}
      pr-number: ${{ needs.release-please.outputs.pr_number }}
    secrets: inherit
  modify-release:
    needs: release-please
    uses: ./.github/workflows/modify-release.yml
    if: ${{ needs.release-please.outputs.to_modify_release }}
    with:
      version: ${{ needs.release-please.outputs.version }}
      tag_name: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit